### ISSUE TITLE
什么都没有是认真的吗

### ISSUE THREAD

**Issue by Zhangbeibei123** [ZNan-Chen/AGLNet#1]
是认真的吗

**Comment by ZNan-Chen** [comment]
Thank you for your attention. The inference results have been published, but since our paper is still under review, we will release the code as soon as possible after the paper is accepted.

**Comment by Zhangbeibei123** [comment]
如何查看
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月14日(星期天) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZNan-Chen/AGLNet] 什么都没有是认真的吗 (Issue #1)














 
关闭 #1 已完成。
 
—
直接回复此邮件，在GitHub上查看，或取消订阅。
您收到此消息是因为您创作了该线程。Message ID: ***@***.***&gt;

**Comment by Zhangbeibei123** [comment]
祝你发表一切顺利，如果可以，请在代码发布后第一时间通知我，谢谢
